title: "Vaishnavi Sreenivasa"
description: "Data engineer · CMU Heinz · Finance, analytics & impact at scale"
theme: jekyll-theme-cayman

# Navigation
navigation:
  - title: About
    url: /
  - title: Projects
    url: /projects
  - title: Contact
    url: /contact
  - title: Work
    url: /work

